# Generated by Django 4.2.3 on 2023-08-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='github',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='persons',
            name='instagram',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='persons',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persons',
            name='threads',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='persons',
            name='twitter',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='bio',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
