# Generated by Django 4.2.3 on 2023-08-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persons', '0002_persons_github_persons_instagram_persons_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='email',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
