# Generated by Django 4.2.3 on 2023-08-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Persons', '0004_formentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='age',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='github',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='job',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='threads',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='twitter',
        ),
    ]
